#+title: QuaSi: Quantum Hardware Simulation Framework

[[https://github.com/tqsd/QuaSi/actions/workflows/pylint.yml/badge.svg?branch=master]]


Framework for quantum simulations using realistic device models.

* Framework Design

** Signals
Signals represent interface between the devices.
Each signal type should inherit from the Abstract Base Class ~GenericSignal~,
implemented in [[file:./quasi/signals/generic_signal.py][quasi/signals/generic_signals.py]].


** Devices
Each device design stems from the Abstract Base Class ~GenericDevice(ABC)~,
implemented in [[file:./quasi/devices/generic_device.py][quasi/devices/generic_device.py]].

* Usage
Currently QuaSi is in development process, so you should use it as a developer.
Please read the notes on Conributing.
** GUI
+ in the *gui* branch
The gui is implemented in [[quasi/gui]] directory. To run the gui
execute the ~main.py~ file by:
#+begin_src bash :results output
flet main.py
#+end_src

Flet is a flutter wrapper library.



* Contributing

** Developing

In order to develop the framework:
1. clone the repository,
2. create a new branch,
3. create new virtual environment:
   + with ~virtualenv~
      #+begin_src bash
   virtualenv .venv
   source .venv/bin/activate
      #+end_src
   + or with conda:
     TODO

4. install the package in editable mode (this also installs all of the required packages):
   #+begin_src bash
   pip install -e .
   #+end_src

