from typing import List, Tuple
from qureed.simulation import Simulation
from qureed.devices.clocks.constant_clock import ConstantClock
from qureed.devices.optical_sources.ideal_n_photon_source import (
    IdealNPhotonSource,
)
from qureed.devices.waveplates.ideal_tunable_waveplate import (
    IdealTunableWaveplate,
)
from random_basis_trigger import RandomBasisTrigger
from random_basis_detection import RandomBasisDetection
from custom_fiber import CustomFiber


def quantum_key_check(alice_key: List[int], bob_key: List[int]) -> None:
    """
    Compares the quantum keys generated by Alice and Bob.

    This function trims both keys to the same minimum lenght, compares each
    bit, and prints statistics including mismatches and accuracy.

    Arguments:
    ----------
    alice_key: List[int]
        The key bits generateb by Alice (sender)
    bob_key: List[int]
        The key bits generateb by Bob (sender)
    """
    min_len = min(len(alice_key), len(bob_key))
    alice_trimmed = alice_key[:min_len]
    bob_trimmed = bob_key[:min_len]

    mismatches = sum(a != b for a, b in zip(alice_trimmed, bob_trimmed))
    accuracy = (min_len - mismatches) / min_len if min_len > 0 else 0

    print("\nQuantum Key Check")
    print("----------------------")
    print(f"Alice's key: {alice_trimmed}")
    print(f"Bob's key:   {bob_trimmed}")
    print(f"Key length:  {min_len}")
    print(f"Mismatches:  {mismatches}")
    print(f"Accuracy:    {accuracy * 100:.2f}%")


def BB84() -> None:
    """
    Simulates the BB84 Quantum Key Distribution protocol using polarization
    encoding.

    This setup involves:
    - A sender (Alice) who randomly generates bits and bases and encodes them
      into single-photon polarization states.
    - A receiver (Bob) who randomly selects measurement bases, measures
      incoming photons, and stores the results.
    - Classical post-processing steps where bases are compared and matching
      outcomes are kept.

    Devices used:
    - `ConstantClock`: for timing control
    - `RandomBasisTrigger`: random bit + basis generator and waveplate
      controller (Alice)
    - `IdealNPhotonSource`: emits single photons when triggered
    - `IdealTunableWaveplate`: applies RY polarization rotations
    - `RandomBasisDetection`: random basis selector and detector (Bob)

    The simulation runs until a fixed time, and the resulting keys are
    compared.
    """
    FREQUENCY = 10

    # --- ALICE SETUP ---
    A_clock = ConstantClock()
    A_clock.set_property("frequency", FREQUENCY)
    A_rbt = RandomBasisTrigger()
    A_rbt.set_property("frequency", FREQUENCY)
    A_sps = IdealNPhotonSource()
    A_itwp = IdealTunableWaveplate()

    A_clock.connect(A_clock.Ports.tick, A_rbt, A_rbt.Ports.clk)
    A_rbt.connect(A_rbt.Ports.random, A_itwp, A_itwp.Ports.control)
    A_rbt.connect(A_rbt.Ports.trigger, A_sps, A_sps.Ports.trigger)
    A_sps.connect(A_sps.Ports.output, A_itwp, A_itwp.Ports.input)

    # --- BOB SETUP ---
    B_clock = ConstantClock()
    B_clock.set_property("frequency", FREQUENCY)
    B_rbd = RandomBasisDetection()
    B_itwp = IdealTunableWaveplate()

    B_clock.connect(B_clock.Ports.tick, B_rbd, B_rbd.Ports.clk)
    B_rbd.connect(B_rbd.Ports.rnd, B_itwp, B_itwp.Ports.control)
    B_itwp.connect(B_itwp.Ports.output, B_rbd, B_rbd.Ports.input)

    # --- INTERCONNECTION ---

    fiber = CustomFiber()
    fiber.set_property("length", 1000)

    # Connect Alice's waveplate output to Bob's waveplate input
    A_itwp.connect(A_itwp.Ports.output, fiber, fiber.Ports.input)
    fiber.connect(fiber.Ports.output, B_itwp, B_itwp.Ports.input)

    # Classical communication: Basis confirmation
    A_rbt.connect(
        A_rbt.Ports.basis_confirm_out, B_rbd, B_rbd.Ports.basis_confirm_in
    )
    B_rbd.connect(
        B_rbd.Ports.basis_confirm_out, A_rbt, A_rbt.Ports.basis_confirm_in
    )

    # --- RUN SIMULATION ---
    Simulation().run(until=15)

    # --- VERIFY QUANTUM KEY AGREEMENT ---
    quantum_key_check(A_rbt.quantum_key, B_rbd.quantum_key)


if __name__ == "__main__":
    BB84()
