"""
Strings denote the specific image to be used
"""
SINGLE_PHOTON_SOURCE = "single_photon_source.png"
N_PHOTON_SOURCE = "n_photon_source.png"
SQUEEZED_PHOTON_SOURCE = "ideal_squeezed_photon_source.png"
BEAM_SPLITTER = "beam_splitter.png"
WIGNER_CONTROL = "wigner_contorl.png"
SIMPLE_TRIGGER = "simple_trigger.png"
HISTOGRAM = "histogram.png"
PLAY = "play.png"
LASER = "laser.png"
FIBER = "fiber.png"
CLOCK_TRIGGER = "clock_trigger.png"
EXCITATION = "excitation.png"
DETECTOR = "detector.png"
