"""
Strings denote the specific image to be used
"""

SINGLE_PHOTON_SOURCE = "single_photon_source.png"
N_PHOTON_SOURCE = "n_photon_source.png"
SQUEEZED_PHOTON_SOURCE = "ideal_squeezed_photon_source.png"
BEAM_SPLITTER = "beam_splitter.png"
WIGNER_CONTROL = "wigner_contorl.png"
SIMPLE_TRIGGER = "simple_trigger.png"
HISTOGRAM = "histogram.png"
PLAY = "play.png"
LASER = "laser.png"
FIBER = "fiber.png"
CLOCK_TRIGGER = "clock_trigger.png"
EXCITATION = "excitation.png"
DETECTOR = "detector.png"
PHASE_SHIFT = "phase_shift.png"
SORTER = "sorter.png"
OPTICAL_MEMORY_DECODER = "optical_memory_decoder.png"
ENCODER = "encoder.png"
MESSAGES = "messages.png"
SWITCH = "switch.png"
REVERSE_SWITCH = "reverse_switch.png"
FUNNEL = "funnel.png"
NON_DESTRUCTIVE_MEASUREMENT = "non_destructive_measurement.png"
PHASE_SHIFT_DECODER = "phase_shift_decoder.png"
DISPLACE = "displace.png"
NV_CENTER = "nv_center.png"
