from typing import Dict, Tuple, Union, Any, cast

from qureed.simulation.simulation import Simulation
from .generic_beam_splitter import GenericBeamSplitterDevice
from qureed.devices.wrappers import des_proc
from qureed.signals import QuantumOpticalPulseSignal, QOPSignalType


class PerfectOverlapBeamSplitter(GenericBeamSplitterDevice):
    """
    Perfect Overlap Beam Splitter Device

    This device models a non-polarizing beam splitter with perfect temporal
    overlap of input photons. It processes incoming `QuantumOpticalPulseSignal`
    signalsf from ports `A` and `B`. If only one input signal is received, a
    vacuum partner is generated to maintain the expected behavior. The signals
    are then sent through a beam splitter operation defined in `PhotonWeave`
    backend.

    Ports:
    ------
    - A (input): Receives quantum optical pulse signals
    - B (input): Receives quantum optical pulse signals
    - C (output): Emits signal resulting from the transformation of
        A and B
    - D (output): Emits signal resulting from the tranfrormation of
        A and B

    Properties:
    -----------
    - eta: float
        The splitting ratio of beam splitter.
        (pi/4 corresponds to 50:50 split.)

    Backend Compatibility:
    ----------------------
    - photon_weave: supported via `_generate_signals_photon_weave` and
        `_mixing_process_photon_weave` methods.

    Example:
    --------
    >>> bs = PerfectOverlapBeamSplitter()
    >>> bs.set_property("eta", 0.785) # 50:50 beam splitter
    """

    def __init__(self, uid=None, **kwargs):
        super().__init__(uid, **kwargs)
        self._buffer: Dict[Tuple[float, float], Dict[str, Any]] = {}
        self.delay = 1.5e-10

    @property
    def gui_name(self) -> str:
        return "Perfect Overlap Beam Splitter"

    def _port_translation(
        self, port: Union[str, GenericBeamSplitterDevice.Ports]
    ) -> GenericBeamSplitterDevice.Ports:
        """
        Translates input ports to output ports. Input port `A` is tranclated
        to output port `C` and input port `B` is translated to output port `D`.

        Arguments:
        ----------
        port: Union[str, GenericBeamSplitterDevie.Ports]
            Input port to translate

        Returns:
        --------
        GenericBeamSplitterDevice.Ports :
            The translated output port
        """
        if port == self.Ports.A:
            return self.Ports.C
        return self.Ports.D

    def _store_and_send_starts(
        self,
        starts: Dict[
            float,
            Dict[GenericBeamSplitterDevice.Ports, QuantumOpticalPulseSignal],
        ],
    ) -> None:
        """
        Stores `START` signals in the internal buffer and forwards
        them to output ports with delay.

        This method prepares a buffer entry that groups all `START` signals
        received at a give central wavelength. Each signal is sent to the
        output port mapped via `_port_translation`. The buffer entry is used
        later to match incoming `END` signals and complete the photon pair
        lifecycle.

        Arguments:
        ----------
        starts: Dict[float, Dict[Ports, QuantumOpticalPulseSignal]]
            A mapping from central wavelength to a dictionary containing input
            port to `START` signal mappings.

        Side effects:
        -------------
        - Appends a new dictionary to `self._buffer` containing the signals
        - Sends `START` signals to output ports with delay.

        """
        ts = self.sim_env.now
        for wl, signals in starts.items():
            for sig in [starts[wl][k] for k in signals.keys()]:
                sig.metadata[f"_{id(self)}_ts"] = ts

            entry = {
                "starts": signals,
                "ends": {},
            }
            self._buffer[(ts, wl)] = entry
            for port, signal in signals.items():
                self._send_with_delay(self._port_translation(port), signal)

    def _generate_signals(
        self, signal: QuantumOpticalPulseSignal
    ) -> Tuple[QuantumOpticalPulseSignal, QuantumOpticalPulseSignal]:
        """
        Dispatches signal generation to the backend-specific impementation.

        This is used to synthesize a matching `START` signal (vacuum) when
        only one `START` is received for a given wacelength. The backend-
        specific method is determined by the currently active simulation
        backend.

        Arguments:
        ----------
        signal : QuantumOpticalPulseSignal
            The original START signal received on one port.

        Returns:
        --------
        Tuple[QuantumOpticalPulseSignal, QuantumOpticalPulseSignal]
            A pair of `START` and `END` signals generated by the backend, to
            emulate a missing input.
        """
        method_name = f"_generate_signals_{Simulation().backend}"
        method = getattr(self, method_name, None)
        if method is None:
            raise NotImplementedError(
                "_generate_starts method not implemented for backend "
                f"{Simulation().backend}; expected method {method_name}"
            )
        return method(signal)

    def _mixing_process(
        self,
        signal_1: QuantumOpticalPulseSignal,
        signal_2: QuantumOpticalPulseSignal,
    ):
        """
        Dispatches the beam splitter mixing process to a backend-specific
        method.

        The operation combines two temporally overlapping quantum optical
        signals and produces a pair of output signals based on the beam
        splitter transformation.

        Arguments:
        ----------
        signal_1 : QuantumOpticalPulseSignal
            Signal received on port `A`
        signal_2 : QuantumOpticalPulseSignal
            Signal received on port `B`

        returns:
        --------
        Tuple[QuantumOpticalPulseSignal, QuantumOpticalPulseSignal]
            Transformed output signas for ports C and D.
        """
        method_name = f"_mixing_process_{Simulation().backend}"
        method = getattr(self, method_name, None)
        if method is None:
            raise NotImplementedError(
                "_process_mixing method not implemented for backend "
                f"{Simulation().backend}; expected method {method_name}"
            )
        return method(signal_1, signal_2)

    def _send_with_delay(self, port, signal):
        def __send():
            yield self.sim_env.timeout(self.delay)
            self.send(port, signal)

        self.sim_env.process(__send())

    def _extract_starts(
        self,
        received: list[
            Tuple[QuantumOpticalPulseSignal, GenericBeamSplitterDevice.Ports]
        ],
    ) -> Dict[
        float, Dict[GenericBeamSplitterDevice.Ports, QuantumOpticalPulseSignal]
    ]:
        """
        Extracts and groups `START` signals from the list of received signals.

        The method scans the received list and collects all `START` signals,
        grouping them by their `central_wavelength`.

        Arguments:
        ----------
        received : List[Tuple[
                         QuantumOpticalPulseSignal,
                         GenericBeamSplitterDevice.Ports]]
            List of (signal, port) putles received at this simulation step

        Returns:
        --------
        Dict[float, Dict[GenericBeamSplitterDevice.Ports,
                         QuantumOpticalPulseSignal]]
            Dictionary mapping wavelength to a dictionary mapping port to
            signal.
        """
        starts: Dict[
            float,
            Dict[GenericBeamSplitterDevice.Ports, QuantumOpticalPulseSignal],
        ] = {}
        for signal, port in received:
            if signal.type is QOPSignalType.START:
                wl = signal.metadata.get("central_wavelength", -1)
                starts.setdefault(wl, {})[port] = signal
        return starts

    def _complete_missing_starts(
        self,
        starts: Dict[
            float,
            Dict[GenericBeamSplitterDevice.Ports, QuantumOpticalPulseSignal],
        ],
    ) -> Dict[
        float, Dict[GenericBeamSplitterDevice.Ports, QuantumOpticalPulseSignal]
    ]:
        """
        Fills in mising `START` signals by generating synthetic partners when
        one port received a signal for a given wavelength.

        This ensures that the beam splitter always operates on a complete pair
        of signals. The generated signal represents a vacuum state.

        Arguments:
        ----------
        starts: Dict[float, Dict[Ports, QuantumOpticalPulseSignal]]
            The partially completed dictionary of detected `START` signals.

        Returns:
        --------
        Dict[float, Dict[Ports, QuantumOpticalPulseSignal]]
            The same dictionary, but with all wavelengths now having signals
            from both ports.

        Notes:
        ------
        - The metadata of the created signal is updated with the _gen flag
          with unique id of this device.
        """
        for wl, signals in list(starts.items()):
            if len(signals) == 1:
                port = next(iter(signals))
                other = self.Ports.B if port is self.Ports.A else self.Ports.B
                generated_start, _ = self._generate_signals(signals[port])
                generated_start.metadata[f"_{id(self)}_gen"] = True
                starts[wl][other] = generated_start
        return starts

    def _extract_ends(
        self,
        received: list[
            Tuple[QuantumOpticalPulseSignal, GenericBeamSplitterDevice.Ports]
        ],
    ) -> list[Dict[str, Any]]:
        """
        Matches `END` signals to their corresponding buffered `START` signal,
        allowing the device to locate and correct buffer entry and collect
        signals until both `END`s are received.


        Parameters:
        -----------
        received: List[Tuple[QuantumOpticalPulseSignal, Ports]]
            List of received signals.

        Returns:
        --------
        List[Dict[str, Any]]
            List of buffer entries (previously created via
            `_store_and_send_starts`) that now have both END signals and are
            ready for mixing.
        """
        ready = []
        for signal, port in received:
            if signal.type is QOPSignalType.END:
                # other_port = "A" if port == "B" else "B"
                other_port = (
                    self.Ports.A if port is self.Ports.B else self.Ports.B
                )
                wl = signal.metadata.get("central_wavelength", -1)
                ts = signal.pair.metadata[f"_{id(self)}_ts"]
                entry = self._buffer[(ts, wl)]
                entry.setdefault("ends", {})[port] = signal
                md = entry["starts"][other_port].metadata
                gen_key = f"_{id(self)}_gen"
                if gen_key in md:
                    entry["ends"][other_port] = entry["starts"][
                        other_port
                    ].pair
                if entry not in ready:
                    ready.append(entry)
        return ready

    def _mix_and_send(
        self,
        entry: Dict[
            str,
            Dict[GenericBeamSplitterDevice.Ports, QuantumOpticalPulseSignal],
        ],
    ) -> None:
        """
        Mixes the two signals in a buffer entry if both `END`s are present,
        and sends the output singals to ports `C` and `D`.

        The original singals are also removed from `_buffer`.

        Arguments:
        ----------
        entry : Dict[str, Dict[Ports, QuantumOpticalPulseSignal]]
           Entry containing the signals to mix and send
        """
        if set(entry.get("ends", {})) == {self.Ports.A, self.Ports.B}:
            sigA = entry["starts"][self.Ports.A]
            sigB = entry["starts"][self.Ports.B]
            self._mixing_process(sigA, sigB)
            self._send_with_delay(self.Ports.C, sigA)
            self._send_with_delay(self.Ports.D, sigB)
            wl = sigA.metadata["central_wavelength"]
            ts = sigA.metadata[f"_{id(self)}_ts"]
            del self._buffer[(ts, wl)]

    @des_proc
    def proc(self):
        """
        Main simulation process for this Beam Splitter.

        This coroutine runs in the SimPy event loop. It Processes `START` and
        `END` signals from ports `A` and `B`. `START` signals are buffered and
        potentially completed with synthetic signals. `END` signals trigger the
        mixing operation once both are present.

        A fixed delay is applied before emitting signals, simulating, the time
        light needs to travel through the beamsplitter.

        Signal Flow:
        ------------
        - Input: `A` (`QuantumOpticalPulseSignal`)
        - Input: `B` (`QuantumOpticalPulseSignal`)
        - Output: `C` (`QuantumOpticalPulseSignal`)
        - OInput: `D` (`QuantumOpticalPulseSignal`)

        Behavior:
        ---------
        - Waits for either `START` or `END` input signals
        - If `START` signal is received:
          - Stores the signals, potentially creates a synthetic signal for
            the other port, sends the `START` signals with delay, but
            unaffected state.
        - If `END` signal is received:
          - Finds the correct pair of signals, mixes them and sends them out
            with the delay.
        """
        while True:
            received = yield from self.any_receive(self.Ports.A, self.Ports.B)

            starts = self._extract_starts(received)
            completed_starts = self._complete_missing_starts(starts)
            if completed_starts:
                self._store_and_send_starts(completed_starts)

            to_mix = self._extract_ends(received)
            print(len(to_mix))
            for entry in to_mix:
                self._mix_and_send(entry)

    # <<< PHOTON WEAVE SPECIFIC METHODS >>>

    def _generate_signals_photon_weave(
        self, signal
    ) -> Tuple[QuantumOpticalPulseSignal, QuantumOpticalPulseSignal]:
        """
        Generate Signals for the photon_weave backend.

        Creates a new signal with a vacuum state, and
        copies metadata from the given signal.

        Arguments:
        ----------
        signal: QuantumOpticalPulseSignal
            A signal to copy metadata from

        Returns:
        --------
        Tuple[QuantumOpticalPulseSignal, QuantumOpticalPulseSignal]
           Newly created signal pair
        """
        from photon_weave.state.envelope import Envelope

        new_envelope = Envelope()
        return QuantumOpticalPulseSignal.create_pair(
            payload=new_envelope,
            metadata=signal.metadata,
        )

    def _mixing_process_photon_weave(
        self,
        signal_1: QuantumOpticalPulseSignal,
        signal_2: QuantumOpticalPulseSignal,
    ) -> None:
        """
        Applies Beam Splitting operation to the envelopes contained in the two
        given two signals.

        Arguments:
        ----------
        signal_1: QuantumOpticalPulseSignal
            signal received on port A
        signal_2: QuantumOpticalPulseSignal
            signal received on port B
        """
        from photon_weave.state.envelope import Envelope
        from photon_weave.state.composite_envelope import CompositeEnvelope
        from photon_weave.operation import Operation, CompositeOperationType

        envelope_1 = cast(Envelope, signal_1.payload)
        envelope_2 = cast(Envelope, signal_2.payload)

        ce = CompositeEnvelope(envelope_1, envelope_2)

        op = Operation(
            CompositeOperationType.NonPolarizingBeamSplitter,
            eta=self.get_property("eta"),
        )
        ce.apply_operation(op, envelope_1.fock, envelope_2.fock)
